### ISSUE TITLE
"Find out more" needs updating - links below the initial community links

### ISSUE THREAD

**Issue by SomeoneElseOSM** [switch2osm/switch2osm#101]
https://switch2osm.org/find-out-more/

In addition to the community links already mentioned in https://github.com/switch2osm/switch2osm.github.io/issues/100 , a number of the resources on there probably need updating.

For example, https://medium.com/devseed/from-google-maps-to-open-source-with-mapbox-and-leaflet-8fc1d971841c? is from 2012 and while it absolutely makes sense to link to Mapbox's how-tos, I'm sure that this isn't the best page.

Also some stuff on https://github.com/nvkelso/geo-how-to/wiki is likely still relevant, but some links from there (e.g. http://geojam.net/static/wicket/doc/ ) are dead.

(that's just the first two issues I noticed - I'm sure that there are more)

The page is "about the right length" as it stands, so it may make sense to e.g. link to a new page about "how to navigate the OSM community" below a couple of top links, and similarly link to an "other tutorials" page where we can push more links of that type.

**Comment by ArloJamesBarnes** [comment]
Under 'Books', there's
* OpenStreetMap: A Beginner’s Guide (English/French)
which from the link is the same as this one that an author said had been obsoleted: https://redd.it/9b50i4

**Comment by SomeoneElseOSM** [comment]
I've updated the "find out more" page.
