### ISSUE TITLE
Add content about how mapnik and renderd connect to postgis

### ISSUE THREAD

**Issue by remyleone** [switch2osm/switch2osm#149]
Maybe a schema would be useful.
But at the moment I have trouble understanding how renderd and mapnik connect to the postgis database.
In particular, I'm not sure to see where the rendering backend connects to the database backend.

I'm ready to add the content if I can get more explanation about which software connect to postgis directly and perform query on the database.

**Comment by bradh** [comment]
Is this in the "serving tiles" context? Can you explain more about what you are looking for (e.g. what is the problem you are trying to solve)?

**Comment by remyleone** [comment]
In Configure renderd on https://switch2osm.github.io/serving-tiles/manually-building-a-tile-server-ubuntu-22-04-lts/ for instance it would be helpful to add explicit configuration for the database backend. How does the rendered daemon knows to which database to connect to gather the data required for the rendering?

Maybe it would be helpful to have a diagram on all the tutorials that shows the different components and how they connect to one another. (renderd, postgis, mapnik, ...)

**Comment by SomeoneElseOSM** [comment]
> Maybe it would be helpful to have a diagram on all the tutorials that shows the different components and how they connect to one another. (renderd, postgis, mapnik, ...)

Another article (with a diagram) linked to from all the tutorials would also do the job, and be less work?

**Comment by remyleone** [comment]
Yes it would. But I guess it would also help to put explicit host and port definition in the configuration file for daemon to make the dependencies really explicit.

**Comment by bradh** [comment]
@remyleone I agree with @SomeoneElseOSM that it isn't that useful to provide a detailed explanation of how everything works when most people just want it to make a map (I mean, how deep would you go? database connections, rtree indexing, on-disk storage, threading concepts - there is a lot of tech in this stack!)

For your specific query, there is a high level overview of the toolchain and rendering steps at https://switch2osm.github.io/serving-tiles/ 

In terms of how mapnik gets the data - that is controlled by the stylesheet (`mapnik.xml`) which is generated by carto from `project.mml` and other parts of https://github.com/gravitystorm/openstreetmap-carto (which is linked from the stylesheet part of the guide). Its configured near the top - as `osm2pgsql`, which is expanded in each Layer definition as part of the `Datasource`. 

Note that this isn't the rendering daemon (renderd) - this in the mapnik context.

If you want to modify the carto script to select from a different source, see https://cartocss.readthedocs.io/en/latest/mml.html?highlight=Datasource#datasource for the syntax. However that would only be needed if you were doing a different kind of build (say with a rendering cluster working off a single database on a different machine) which is well beyond what I think the current instructions aim at, and would be overly complicated for most people.

Does that help to solve your problem, or give you enough to work from?

**Comment by SomeoneElseOSM** [comment]
I'll close this as "not planned" in the absence of anything specific to look at.
