### ISSUE TITLE
ERROR : must be owner of table planet_osm_nodes

### ISSUE THREAD

**Issue by AkwabaMaps** [switch2osm/switch2osm#160]
Hi, 

I replaced yourserveripaddress by the address of the server but I get : 

Not Found
The requested URL was not found on this server.

any tips?

**Comment by Firefishy** [comment]
Are your getting the `ERROR : must be owner of table planet_osm_nodes` error?

**Comment by SomeoneElseOSM** [comment]
Maybe this was "trying to do everything as root"?  People have tripped up over that, even though  the instructions do warn against it.

Without more information, there's not much we can do.
