### ISSUE TITLE
Serving tiles in other crs then EPSG:3857

### ISSUE THREAD

**Issue by rduivenvoorde** [switch2osm/switch2osm#214]
Thanks for the write up !

I am succesfully serving tiles (using Debian 12 now, with some minor fixes) as written on https://switch2osm.org/serving-tiles/manually-building-a-tile-server-debian-11/

But I wonder what I need to do to create a Tile cache in our national CRS (EPSG:2899 / The Netherlands, we even have a 'national tile schema').
Do I need to load data in EPSG:28992 (in another schema)?
Is that another Mapnik configuration (so mapnik will request crs and postgis wil reproject)?

I think this a use case in which other people potentially are interested? 

I've done this many years ago, but with a totally other tool chain. I think it is more efficient to stick to current switch2osm tool chain.

Any input appreciated, happy to do the write up here later

**Comment by SomeoneElseOSM** [comment]
Firstly good to hear that Debian 12 is working well now (when I last tried it a couple of years ago it wasn't quite there yet).  More documentation has been added to github; see https://github.com/openstreetmap/mod_tile/pull/309 and https://github.com/openstreetmap/mod_tile/issues/310 .

If I read https://github.com/openstreetmap/mod_tile/issues/3 correctly it should be just a style-dependent thing, and further digging finds lots of references to using projections and reprojecting at e.g. https://gis.stackexchange.com .

I've not see a lot of people asking for alternate projections here - it's more of a stackexchange question than a "set up a database for the first time" one, but if you do pull something together put it in an OSM diary entry or similar and we'll have a look!
