### ISSUE TITLE
Further changes in OSM Carto

### ISSUE THREAD

**Issue by dch0ph** [switch2osm/switch2osm#271]
Following the changes in OSM Carto to add SQL functions to the style in 5.9.0, I noticed that a new merge also introduces a breaking change to the installation - use of the `osm2pgsql` flex input.

I suspect that the development version of OSM Carto will be a bit bleeding edge ahead of the next release (v6.0?). It might be safest to recommend unpacking a zip from the latest release (5.9.0) rather git cloning the repository? [It's unfortunate that the releases don't include a pre-compiled XML, which would save installing carto.]

**Comment by SomeoneElseOSM** [comment]
Thanks for spotting this!

For 5.9.0, rather than downloading a zip, getting people to checkout a release should work, which should get them to https://github.com/gravitystorm/openstreetmap-carto/tree/v5.9.0 .  However, if the flex stuff works (and I don't see why it shouldn't, since the version of it that pnorman did ages ago seemed to work just fine for me when I tested it), then going forward I can't see why we can't point at that version.  Obviously various pages here will need changing to say e.g. "osm2pgsql -O flex" etc. and there may be some gotchas on some OSes not caught by https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md .

I suspect that the Docker build will fail because it depends on a set of external instructions in the dockerfile - unless those have been updated they'll be wrong both for 5.9.0 and for the flex version.

**Comment by SomeoneElseOSM** [comment]
OK, here we go.  I've changed the Debian 12 version to include:

    mkdir ~/src
    cd ~/src
    git clone https://github.com/gravitystorm/openstreetmap-carto
    cd openstreetmap-carto
    git pull --all
    git switch --detach v5.9.0

Can you give that a go and see if it works for you?  If it does I'll update Ubuntu 22.04, 24.04 and Debian 11 as well.  The other one that might need looking at is Docker - https://github.com/Overv/openstreetmap-tile-server/blob/master/Dockerfile is 5.4.0, which should work, but isn't especially up to date.

**Comment by dch0ph** [comment]
> For 5.9.0, rather than downloading a zip, getting people to checkout a release should work,

Yes, but you presumably end up downloading the entire repo. Could you not use:
`wget https://github.com/gravitystorm/openstreetmap-carto/archive/refs/tags/v5.9.0.zip`
?

> However, if the flex stuff works (and I don't see why it shouldn't, since the version of it that pnorman did ages ago seemed to work just fine for me when I tested it), then going forward I can't see why we can't point at that version.

Yes, it should work fine. I just worry that there is likely to be some breakage (e.g. old versions of osm2pgsql) and some degree of "bleeding edgeness" as new ideas around the flex input are tested. [PRs all look to be going into the master branch rather than a development branch.] 

> I suspect that the Docker build will fail because it depends on a set of external instructions in the dockerfile - unless those have been updated they'll be wrong both for 5.9.0 and for the flex version.

Given that it is using a fixed OSMCarto version, it might be OK. The Dockerfile in the OSM Carto repo is not being maintained, and so can't be recommended.

**Comment by SomeoneElseOSM** [comment]
Just picking up a couple of those points:

> old versions of osm2pgsql

All the switch2osm pages suggest using OS-distributed versions of things where possible, so a particular flavour of the guide wouldn't be changed to suggest building a "flex" version unless there was a chance of it working - older versions of the guides get retired from the index as it becomes impractical to update them.

> The Dockerfile in the OSM Carto repo is not being maintained

It's not that dockerfile, it's the one at https://github.com/Overv/openstreetmap-tile-server .  That seems to be based around OSM Carto 5.4.0, so isn't dependent on the "bleeding edge" of the repository and hence my "I suspect that the Docker build will fail" was probably wrong.

> Could you not use: wget https://github.com/gravitystorm/openstreetmap-carto/archive/refs/tags/v5.9.0.zip

The advantage of having people clone the repository is that that they're still connected to the repository afterwards.  If they want to try another version, they easily can.  The entire thing is only 80MB and over half of that is subsequently downloaded fonts :)

**Comment by SomeoneElseOSM** [comment]
I'll close this, because the pages for each of the OSes on the [menu](https://switch2osm.org/serving-tiles/) are updated.
