### ISSUE TITLE
add "Loading OSM data" guide

### ISSUE THREAD

**Issue by matkoniecz** [switch2osm/switch2osm#34]
As I understand from IRC discussion this project is intended to replace current switch2osm.org.

So it would preferable to avoid losing data, including https://switch2osm.org/loading-osm-data/ (that at least I used multiple times).

Would it be OK to make PR that at first copies https://switch2osm.org/loading-osm-data/ guide and improves it by providing instructions directed for Ubuntu 16.04 rather for Ubuntu 14 and Ubuntu 12 (Ubuntu 12 reached its EOL already, Ubuntu 14 will likely reach before https://github.com/switch2osm/switch2osm.github.io will replace current https://switch2osm.org/ )?

**Comment by pnorman** [comment]
My strong preference is to restructure serving tiles content. I thought I had outlined how, but can't see a reference. I'll check my notebooks tomorrow, but briefly

- loading OSM data on its own page (gets you to OSM data in a database named `gis`)
- rendering tiles (renderd + mod_tile)
- using a style design suite

This was planned before osm-carto switched, and it was already a difficult question what style would be used as an example for rendering tiles

**Comment by SomeoneElseOSM** [comment]
To explain some of this ancient history to people who may have still been in junior school at the time, https://switch2osm.org/loading-osm-data/ had a bit more "large server" and "optimisation" information in it than e.g. https://switch2osm.org/serving-tiles/manually-building-a-tile-server-ubuntu-22-04-lts/ does now.  That's deliberate, as the "getting started" guides here deliberately try and specify the minimum changes that will work (hence Docker, and the turnkey renderd/mod_tile process on recent Debian/Ubuntu releases).

Other guides out there (for example https://www.linuxbabe.com/linux-server/osm-openstreetmap-tile-server-ubuntu-22-04 ) have more "large server" content, and there's plenty of postgres/postgis optimisation information at stickoverflow et al.

Of @pnorman 's notes above "using a style design suite" is still very much an outstanding issue. https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md has some suggestions but I'm not sure whether it all works end to end on all platforms.
