### ISSUE TITLE
clarify purpose of this repo

### ISSUE THREAD

**Issue by matkoniecz** [switch2osm/switch2osm#35]
As I understand from IRC discussion this project is intended to replace current switch2osm.org.

https://github.com/switch2osm/switch2osm.github.io#switch2osm currently has 

> This repository is not what currently powers switch2osm.org, but is some ideas in the early conceptual stage.

It may be a good idea to explicitly mention whatever this repo is a WIP replacement for the current version of switch2osm.org or not.

**Comment by pnorman** [comment]
It would be a WIP to be a replacement if people were working on it.

**Comment by harry-wood** [comment]
I think @matkoniecz original question/request for clarification would be answered with something like this:
_"This repository is a jekyll static content site which is intended to power switch2osm.org in future. Currently switch2osm.org content is held in a wordpress install. We would like to make it available to maintain via pull requests on github. This repo also contains some ideas for content changes in the early conceptual stage."_

...but this raises my own question/idea. Maybe the repo _shouldn't_ contain ideas for content changes just yet. I mean we could initially develop a Jekyll site with _no content changes_, get over the hump of transitioning to this for the live site first.

**Comment by SomeoneElseOSM** [comment]
This issue predates the move from Wordpress to Jekyll, and therefore can be closed.
