### ISSUE TITLE
External sources, articles

### ISSUE THREAD

**Issue by loicortola** [switch2osm/switch2osm#38]
When considering to switch2osm, companies often have doubts on the quality of the data.
They lack content that says otherwise.

There are so many press articles talking about OSM and people switching to it (I mean Pokemon Go switched out from Google Maps right? Anything is possible ^^). Do you think it would make sense to add a list of featured articles talking about OSM?

The main goal is to show potential switchers that they are not the only one wondering about it.

**Comment by SomeoneElseOSM** [comment]
Since this issue was raise, a whole bunch of other stuff has appeared that would be a better fit for the sort of thing being talked about here, not least https://welcome.openstreetmap.org/  and https://community.openstreetmap.org/ .  I'll close this here.
