### ISSUE TITLE
tutorial issue fix - Manually building a tile server (16.04.2 LTS)

### ISSUE THREAD

**Issue by ghost** [switch2osm/switch2osm#54]
This tutorial manually building a tile server (16.04.2 LTS) has an issue when you reach the "Stylesheet configuration" I kept getting an error about module exports with "sudo npm install -g carto" I fixed it by running.
"curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - && sudo apt-get install -y nodejs"
then
"node -v", which printed v6.14.4
then
"sudo apt-get install -y fonts-noto-cjk fonts-noto-hinted fonts-noto-unhinted fonts-hanazono ttf-unifont"
only then would "sudo npm install -g carto" work.

The first but of the error from before was "/usr/local/lib/node_modules/carto/node_modules/find-up/index.js:5
module.exports = (filename, opts = {}) => {"

I just thought I should let you know for future tutorial users.

**Comment by SomeoneElseOSM** [comment]
Thanks for letting us know - node.js seems to change every other week!

**Comment by SomeoneElseOSM** [comment]
I'll close this as everything mentioned here is now replaced with newer versions
