### ISSUE TITLE
Wrong user in 'osm2pgsql'

### ISSUE THREAD

**Issue by Binternet** [switch2osm/switch2osm#59]
On the great tutorial at https://switch2osm.org/manually-building-a-tile-server-18-04-lts/

You need to run the `osm2pgsql` command as `postgres` user and not as root.

FYI.

**Comment by SomeoneElseOSM** [comment]
Indeed, but which bit of the instructions suggests to you that you should run osm2pgsql as root?

**Comment by Binternet** [comment]
I guess its a bad habit, so I assume that after
`sudo -u postgres -i` you stay as `postgres` for the rest of the installation?

**Comment by pnorman** [comment]
You should **not** run osm2pgsql as the postgres user

**Comment by Binternet** [comment]
So as my chosen _renderaccount_ user? Its not clear for me

בתאריך יום ב׳, 9 בספט׳ 2019, 21:30, מאת Paul Norman ‏<
notifications@github.com>:

**Comment by SomeoneElseOSM** [comment]
Everything after "Installing osm2pgsql" is assumed to be done as the "renderaccount" user (or whatever other account name you chose).  That's why there are bits that say e.g. " Leaving directory ‘/home/renderaccount/src/mod_tile".

**Comment by SomeoneElseOSM** [comment]
Several more guides have been written since 2019 and I've tried to make it clearer with each one that your should not be running things as root.

I'll close this, since I don't think there's much more we can do.
