### ISSUE TITLE
Unclear "Comments or suggestions? Please make contact via IRC at the first instance."

### ISSUE THREAD

**Issue by matkoniecz** [switch2osm/switch2osm#71]
https://switch2osm.github.io/find-out-more/ - is it request to not post comments as issues in this repo here?

**Comment by SomeoneElseOSM** [comment]
That text is more that 12 hours old, and was therefore written when the "live" text was from Wordpress.  We had a number of github pul requests not realising this.  

Now that it's moved, by all means raise issues here, but please don't be disappointed if we end up doing things in a slightly different way (see for example the one suggesting we include Mapbox GL alongside Leaflet and OpenLayers - I suspect we'll need to make a more widespread change than just piecemeal additions to one page.

As I understand it, part of the reasoning behind setting up https://switch2osm.org/ in the first place was to have curated, coherent advice - something that with the bext will in the world the OSM wiki doesn't provide.  For example, last night I had a look at https://wiki.openstreetmap.org/wiki/Vector_tiles and the most charitable thing that I could say was that it wasn't helpful.

**Comment by matkoniecz** [comment]
> please don't be disappointed if we end up doing things in a slightly different way

I will try to not do this - after all it is better to see something done almost like I want it rather than not done at all.

**Comment by SomeoneElseOSM** [comment]
It looks like that text's been removed, so I'll close this.

**Comment by SlowMo24** [comment]
Is the website online the most recent version? If so, the text has not been removed.
I, as a non native speaker, also have trouble understanding it. First IRC didn't mean anything to me before searching it. Second who or what is this 'first instance'. Maybe rephrasing with a direct link to where to ask questions would be an alternative?

**Comment by SomeoneElseOSM** [comment]
> Is the website online the most recent version?

Yes

> If so, the text has not been removed.

You're right - that text is still there.  My guess is that I saw some similar text removed from a similar page and closed this in error.

I didn't write that line of text myself, but the original reason for it being there as described at https://github.com/switch2osm/switch2osm.github.io/issues/71#issuecomment-559560389 still applies.  What I think "Please make contact via IRC at the first instance" is trying to say is that people involved in it will usually be around in the regular OSM [IRC](https://wiki.openstreetmap.org/wiki/IRC) channels.  Also, we're hoping that people will maintain translations of the site (see https://github.com/switch2osm/switch2osm.github.io/issues/24 and https://github.com/switch2osm/switch2osm.github.io/issues/92 ), which will avoid confusion over English phrases such as "at the first instance".

**Comment by SomeoneElseOSM** [comment]
Reading this again, the actual text is:

"You can [get involved on GitHub](https://github.com/switch2osm/switch2osm.github.io)
Comments or suggestions? Please make contact via IRC at the first instance."

If anyone is confused by the last sentence presumably they'll just raise an issue here, which I personally don't have a problem with :)
